name: Custom Workflow
on:
  repository_dispatch:
    types: [analysisrequest]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Your Job
        run: |
          # Your job steps go here
          echo " this is working "
